[project]
name = "supply-chain-product-prediction-manu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.0.0",
    "numpy==2.3.0",
    "pandas==2.3.0",
    "scikit-learn==1.7.0",
]
